### PR TITLE
Add an Expect class that saves its position

### PR DESCRIPTION
**Pull request by lf-**
Hi! This implements #25 in a way that is completely neutral to the testing library in use :3

I would recommend reviewing this commit-by-commit, as it was written <del>as-if I was writing it for Gerrit</del> in a way that is split into small, easy to review commits that each pass tests on their own. There's a bunch of refactors in this PR, and although they don't necessarily always purely relate to the task at hand, they gradually build up to making the feature implementation small and nice.

Enjoy :)

I am super excited to be able to use this library for Lix with this feature, and I expect it will become a very well-used tool in our new Python-based integration tests.

### CODE REVIEW

**Review by ezyang — APPROVED** [review]
Looks good, just needs some fixes for the linty bits

**Comment by lf-** [comment]
> Looks good, just needs some fixes for the linty bits

Ah. I wasn't sure how to run the full intended lint suite. It's been years since I've touched any of the Python packaging stuff (pyproject.toml feels super new and unknown to me), is there some way to configure a poetry test/lint command to do that in a uniform way without needing to guess quite as much about the specific project?

**Comment by ezyang** [comment]
If I ever get around to it this repo will switch to using lintrunner. But unfortunately the lint in this repo is a one off `./run_tests.sh`. I've actually never used pyproject.toml linters lol

**Comment by lf-** [comment]
I believe this fixed the lints.

**Comment by ezyang** [comment]
done

**Pull request merged**
